import React from 'react';
import { X, Shield, FileText, Mail, ChevronRight } from 'lucide-react';

interface LegalModalProps {
    type: 'privacy' | 'terms' | 'support';
    onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ type, onClose }) => {
    const getContent = () => {
        switch (type) {
            case 'privacy':
                return {
                    title: 'Privacy Policy',
                    icon: <Shield className="w-6 h-6 text-blue-400" />,
                    content: (
                        <div className="space-y-4 text-gray-300 text-sm leading-relaxed">
                            <p className="font-bold text-white uppercase tracking-widest text-[10px]">1. Information We Collect</p>
                            <p>We collect facial data provided by you through your camera for the sole purpose of AI ranking and analysis. This data is processed in real-time and images are stored securely if you achieve a high score to be displayed on the leaderboard.</p>

                            <p className="font-bold text-white uppercase tracking-widest text-[10px]">2. How We Use Data</p>
                            <p>Your data is used to calculate facial metrics, generate rankings, and manage your account. We do not sell or share your biometric data with third-party advertisers.</p>

                            <p className="font-bold text-white uppercase tracking-widest text-[10px]">3. Payment Information</p>
                            <p>All financial transactions are handled securely by Stripe. We do not store your credit card details on our servers.</p>

                            <p className="font-bold text-white uppercase tracking-widest text-[10px]">4. Your Rights</p>
                            <p>You can request the deletion of your account and associated data at any time by contacting support.</p>
                        </div>
                    )
                };
            case 'terms':
                return {
                    title: 'Terms of Use',
                    icon: <FileText className="w-6 h-6 text-purple-400" />,
                    content: (
                        <div className="space-y-4 text-gray-300 text-sm leading-relaxed">
                            <p className="font-bold text-white uppercase tracking-widest text-[10px]">1. Entertainment Only</p>
                            <p>LooksRank is an AI-powered entertainment application. Rankings and feedback are generated by artificial intelligence and should not be taken as professional medical or aesthetic advice.</p>

                            <p className="font-bold text-white uppercase tracking-widest text-[10px]">2. Coin System</p>
                            <p>Coins are virtual currency used within the app. Purchases are final and non-refundable. We reserve the right to modify coin pricing or utility at any time.</p>

                            <p className="font-bold text-white uppercase tracking-widest text-[10px]">3. User Conduct</p>
                            <p>You agree not to upload offensive or illegal content. We reserve the right to ban users who violate community standards or attempt to exploit the application.</p>

                            <p className="font-bold text-white uppercase tracking-widest text-[10px]">4. Limitation of Liability</p>
                            <p>We are not responsible for any emotional distress or personal decisions made based on AI-generated rankings.</p>
                        </div>
                    )
                };
            case 'support':
                return {
                    title: 'Support',
                    icon: <Mail className="w-6 h-6 text-primary-400" />,
                    content: (
                        <div className="space-y-6 text-center py-4">
                            <div className="flex flex-col items-center gap-3">
                                <div className="p-4 bg-dark-800 rounded-full border border-white/5">
                                    <Mail className="w-8 h-8 text-primary-500" />
                                </div>
                                <div>
                                    <h3 className="text-white font-black text-lg">Need Help?</h3>
                                    <p className="text-gray-400 text-sm mt-1">Our team is here to assist you with payments, account issues, or feedback.</p>
                                </div>
                            </div>

                            <a
                                href="mailto:impulseaiappteam@gmail.com"
                                className="inline-flex items-center gap-2 bg-primary-500 text-white font-black px-6 py-3 rounded-xl hover:brightness-110 active:scale-95 transition-all shadow-lg shadow-primary-500/20"
                            >
                                Contact Support <ChevronRight className="w-4 h-4" />
                            </a>

                            <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest mt-4">
                                Typical response time: 24-48 hours
                            </p>
                        </div>
                    )
                };
        }
    };

    const { title, icon, content } = getContent();

    return (
        <div className="fixed inset-0 z-[110] flex items-center justify-center p-4 bg-black/90 backdrop-blur-sm animate-in fade-in duration-300">
            <div className="w-full max-w-sm bg-dark-900 rounded-[2rem] shadow-2xl border border-white/5 animate-in zoom-in-95 duration-300 flex flex-col max-h-[80vh] overflow-hidden">
                <div className="px-6 pt-6 pb-4 flex justify-between items-center border-b border-white/5 sticky top-0 bg-dark-900 z-10">
                    <div className="flex items-center gap-3">
                        {icon}
                        <h2 className="text-xl font-black uppercase tracking-tight text-white">{title}</h2>
                    </div>
                    <button onClick={onClose} className="p-2 bg-dark-800 rounded-full hover:bg-dark-700 transition-colors border border-white/5">
                        <X className="w-5 h-5 text-gray-400" />
                    </button>
                </div>

                <div className="flex-1 overflow-y-auto p-6 scrollbar-hide">
                    {content}
                </div>

                <div className="p-6 border-t border-white/5 bg-dark-900/50">
                    <button
                        onClick={onClose}
                        className="w-full py-3 bg-dark-800 hover:bg-dark-700 text-white font-bold rounded-xl border border-white/5 transition-all active:scale-95"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};
